<?php

$cities = array(
  //'Alberta',
  'calgary',
  'edmonton',
  'ftmcmurray',
  'lethbridge',
  'hat',
  'peace',
  'reddeer',
  //'British Columbia',
  'cariboo',
  'comoxvalley',
  'abbotsford',
  'kamloops',
  'kelowna',
  'kootenays',
  'nanaimo',
  'princegeorge',
  'skeena',
  'sunshine',
  'vancouver',
  'victoria',
  'whistler',
  //'Manitoba',
  'winnipeg',
  //'New Brunswick',
  'newbrunswick',
  //'Newfoundland and Labrador',
  'newfoundland',
  //'Northwest Territories',
  'territories',
  'yellowknife',
  //'Nova Scotia',
  'halifax',
  //'Ontario',
  'barrie',
  'belleville',
  'brantford',
  'chatham',
  'cornwall',
  'guelph',
  'hamilton',
  'kingston',
  'kitchener',
  'londonon',
  'niagara',
  'ottawa',
  'owensound',
  'peterborough',
  'sarnia',
  'soo',
  'sudbury',
  'thunderbay',
  'toronto',
  'windsor',
  //'Prince Edward Island',
  'pei',
  //'Quebec',
  'montreal',
  'quebec',
  'saguenay',
  'sherbrooke',
  'troisrivieres',
  //'Saskatchewan',
  'regina',
  'saskatoon',
  //'Yukon Territory',
  'whitehorse',
);

$domain = "craigslist.ca";